name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Check pull request
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.18

      - run: npm ci
      - run: npm run build